#!/bin/sh

echo "Content-type: text/plain"
echo ""

command=$(echo "$QUERY_STRING" | awk '{split($0,array,"&")} END{print array[1]}' | awk '{split($0,array,"=")} END{print array[2]}')
aacname=$(echo "$command" | awk '{split($0,array,"%")} END{print array[2]}')
date=$(date)
ipadd=$(ip route get 1 | awk '{print $NF;exit}')
uptime=$(uptime)

if [ $aacname? != "" ]; then
	command=$(echo "$command" | awk '{split($0,array,"%")} END{print array[1]}')
fi

cat <<EOT
OK
EOT

if [ "$command" = "play" ]; then
	ak_adec_demo 16000 2 aac /tmp/$aacname >/dev/null 2>&1
	rm -f /tmp/$aacname
fi
if [ "$command" = "ledon" ]; then
	echo "1" >/sys/user-gpio/WHITE_LED
fi
if [ "$command" = "ledoff" ]; then
	echo "0" >/sys/user-gpio/WHITE_LED
fi
if [ "$command" = "iron" ]; then
	echo "1" >/sys/user-gpio/IR_LED
fi
if [ "$command" = "iroff" ]; then
	echo "0" >/sys/user-gpio/IR_LED
fi
if [ "$command" = "ptzlu" ]; then
	echo "left" >/tmp/ptz.daemon
	echo "up" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzu" ]; then
	echo "up" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzru" ]; then
	echo "right" >/tmp/ptz.daemon
	echo "up" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzld" ]; then
	echo "left" >/tmp/ptz.daemon
	echo "down" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzd" ]; then
	echo "down" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzrd" ]; then
	echo "right" >/tmp/ptz.daemon
	echo "down" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzl" ]; then
	echo "left" >/tmp/ptz.daemon
fi
if [ "$command" = "ptzr" ]; then
	echo "right" >/tmp/ptz.daemon
fi
if [ "$command" = "lookaround" ]; then
	echo "t2p 184 82" >/tmp/ptz.daemon
	sleep 10
	echo "t2p 184 73" >/tmp/ptz.daemon
	sleep 10
	echo "t2p 184 55" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 205 45" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 225 36" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 250 45" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 225 36" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 225 86" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 225 36" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 205 45" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 184 55" >/tmp/ptz.daemon
	sleep 5
	echo "t2p 184 73" >/tmp/ptz.daemon

fi
if [ "$command" = "view0" ]; then
	echo "t2p 184 73" >/tmp/ptz.daemon
fi
if [ "$command" = "view1" ]; then
	echo "t2p 184 82" >/tmp/ptz.daemon
fi
if [ "$command" = "view2" ]; then
	echo "t2p 184 55" >/tmp/ptz.daemon
fi
if [ "$command" = "view3" ]; then
	echo "t2p 205 45" >/tmp/ptz.daemon
fi
if [ "$command" = "view4" ]; then
	echo "t2p 225 36" >/tmp/ptz.daemon
fi
if [ "$command" = "view5" ]; then
	echo "t2p 250 45" >/tmp/ptz.daemon
fi
if [ "$command" = "view6" ]; then
	echo "t2p 330 75" >/tmp/ptz.daemon
fi
if [ "$command" = "view7" ]; then
	echo "t2p 225 86" >/tmp/ptz.daemon
fi
